configName: sam_ha1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMHA1G16AB
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;cryptoauthlib;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMHA1_DFP\2.0.40\samha1ab\atdf\ATSAMHA1G16AB.atdf
