configName: sam_e70_xult
folderName: sam_e70_xult
format_version: v1.0
frameworkPath: C:\H3_bitbucket
processor: ATSAME70Q21B
projectName: sam_e70_xult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME70_DFP\4.10.248
