format_version: v1.0
type: UniqueComponent
attributes: {id: i2c_bootloader}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: BTL_FUSE_PROGRAM_ENABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: BTL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c_bootloader, value: '2048'}
      - type: User
        attributes: {value: '2048'}
  - type: Boolean
    attributes: {id: BTL_TRIGGER_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: BTL_TRIGGER_LEN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: String
    attributes: {id: MEM_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c_bootloader, value: NVMCTRL}
  - type: String
    attributes: {id: PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c_bootloader, value: SERCOM5_I2C}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: btl_I2C_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom5}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM5_I2C}
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvmctrl}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVMCTRL_MEMORY}
- type: ElementPosition
  attributes: {x: '264', y: '221', id: i2c_bootloader}
