configName: sam_l22_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML22N18A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;cryptoauthlib;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML22_DFP\3.2.39\atdf\ATSAML22N18A.atdf
